name: CI

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependancies
        run: yarn

      # - name: Test transpilation, linting and unit
      #   run: yarn test
