name: CI

on:
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependancies
        run: npm i

      - name: Test transpilation and linting
        run: npm run lint
